id: AD617727F
title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:13:06.502856
  last_modified_at: 2022-03-01 05:13:06.502860
